# Generated by Django 5.2.6 on 2025-09-18 10:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=15)),
                ('correo', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('categoria', models.CharField(choices=[('comida', 'Comida'), ('transporte', 'Transporte'), ('entretenimiento', 'Entretenimiento'), ('otros', 'Otros')], max_length=20)),
                ('correo_usuarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario', to_field='correo')),
            ],
        ),
    ]
