# Generated by Django 5.2.6 on 2025-09-23 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_gasto_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='presupuesto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
